### PR TITLE
Add Winget installation reference in the readme

### PR DESCRIPTION
**Pull request by sitiom**
Also, the pull request on winget-pkgs has been merged. You can enable the workflow now

### CODE REVIEW

**Comment by sitiom** [comment]
https://github.com/aiko-chan-ai/DiscordBotClient/actions/runs/7796687530/job/21261817642 `WINGET_TOKEN` secret is missing?

**Comment by aiko-chan-ai** [comment]
@sitiom 
image
idk

**Comment by sitiom** [comment]
It should be located in the repository secrets section, not in the environment variables section:
image

**Comment by aiko-chan-ai** [comment]
oh mb

**Comment by sitiom** [comment]
Can you try rerunning the failed workflow afterwards? Thanks

**Comment by sitiom** [comment]
Now it works:
- https://github.com/microsoft/winget-pkgs/pull/138139

**Pull request merged**
